name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    # putem rula imagini docker
    container: 
      image: node:13.5.0-alpine3.10
      # putem avea env, ports, volumes, options(cpu, host)
    # step-urile vor rula in interiorul containerului, nu in OS acum
    steps:
    - name: Log node version
      run: |
        node -v
        cat /etc/os-release
