name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    # putem rula imagini docker
    services: 
      app:
        image: alialaa17/node-api
        ports:
        - 3001:3000
      mongo:
        image: mongo
        ports:
        - 27017:27017
      # putem avea env, ports, volumes, options(cpu, host)
    # step-urile vor rula in interiorul containerului daca sus in loc de "services" 
    # avem "container"
    steps:
    - name: Post a user
      run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "hello","address": "dwded"}'''
    - name: Get Users
      run: curl http://localhost:3001/api/users
