name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    # steps va rula in interiorul containerului
    steps:
    - name: log node version
      run: node -v
    - name: Step with docker
      # pe langa actions putem rula imagini docker in step
      # in cazult de fata nu va porni un container in container ci alt container in ubuntu
      uses: docker://node:12.14.1-alpine3.10
      # putem suprascrie
      with:
        # in GH Actions entrypoint e doar un path catre executabil. Explicatii info linia 25
        entrypoint: echo
        # <=> CMD din docker. Putem pune doar un argument
        args: Hello World
    - name: Log node version
      # pe langa actions putem rula imagini docker in step
      uses: docker://node:12.14.1-alpine3.10
      # putem suprascrie
      with:
        entrypoint: /usr/local/bin/node
        args: -v
  node-docker:
    runs-on: ubuntu-latest
    # putem rula mai multe imagini docker
    services: 
      app:
        image: alialaa17/node-api
        ports:
        - 3001:3000
      mongo:
        image: mongo
        ports:
        - 27017:27017
      # putem avea env, ports, volumes, options(cpu, host)
    # step-urile vor rula in interiorul containerului daca sus in loc de "services" 
    # avem "container"
    steps:
    - name: Post a user
      run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "hello","address": "dwded"}'''
    - name: Get Users
      run: curl http://localhost:3001/api/users
