name: Shel Commands
#poate fi o lista de evenimente ce declanseaza workflow-ul e.g. [push, pull etc]
on: [push]

#fiecare job va lucra in paralel by default in propriul VM
# se poate seta sa lucreze in serie
jobs: 
  run-shell-command: # numele job-ului
    runs-on: ubuntu-latest # OS-ul runner-ului
    steps: #poate performa o actiune sau o comanda shell(CMD). Aici folosim doar CMD
    - name: echo a string # aici e optional numele
      run: echo "Hello World" # cu run execut comenzi shell
    - name: multiline script
      run: | # folosind acest pipe putem scrie mai multe comenzi pe mai multe linii
        node -v
        npm -v
    - name: python Commands
      run: |
        import platform
        print(platform.processor())
      shell: python # specificam step-ului in ce shell sa ruleze comenzile, default e bash
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"] # setez job-urile in serie, array cu nume de care sa depinda
    steps:
    - name: Directory PowerShell
      run: Get-Location
    - name: Directory bash
      run: pwd
      shell: bash # default in windows e PowerShell